title: blog
author: murcottt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
  
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://github.com/Murcott" # the base hostname & protocol for your site, e.g. http://example.com
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
