theme: minima
title: anecdotes of a lady chef
author: murcott
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a translation
  
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://murcott.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

header_pages:
  - synopsis.md
  - about.md

#collections:
#  pages:
#    output: true
#    permalink: /_pages/:title/

# Include directories/files
# include: ['_pages']
include: 
 - _pages

#paginate: 5
#paginate_path: /blog/page:num/
#plugins:
#  - jekyll-paginate
#show_excerpts: true # set to false to remove excerpts on the homepage

#exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/